// <auto-generated />
using System;
using LoanApp.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoanApp.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LoanApp.Api.Infrastructure.Persistence.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ActorRef")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<Guid?>("OutboxEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("PolicyRevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("OutboxEventId");

                    b.HasIndex("OccurredAtUtc", "Id")
                        .IsDescending();

                    b.HasIndex("EntityType", "EntityId", "OccurredAtUtc", "Id")
                        .IsDescending(false, false, true, true);

                    b.ToTable("AuditEvents", null, t =>
                        {
                            t.HasCheckConstraint("CK_Audit_Outcome", "\"Outcome\" IN ('Succeeded','Denied')");
                        });
                });

            modelBuilder.Entity("LoanApp.Api.Infrastructure.Persistence.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Ssn")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Ssn")
                        .IsUnique();

                    b.ToTable("Customers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Customer_Ssn", "\"Ssn\" ~ '^[0-9]{9}$'");
                        });
                });

            modelBuilder.Entity("LoanApp.Api.Infrastructure.Persistence.LoanApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LastPolicyRevisionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RequestedAmount")
                        .HasPrecision(11, 2)
                        .HasColumnType("numeric(11,2)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.HasIndex("LastPolicyRevisionId");

                    b.ToTable("Applications", null, t =>
                        {
                            t.HasCheckConstraint("CK_Application_Amount", "\"RequestedAmount\" > 0");

                            t.HasCheckConstraint("CK_Application_Currency", "\"Currency\" = 'USD'");

                            t.HasCheckConstraint("CK_Application_Version", "\"Version\" >= 1");
                        });
                });

            modelBuilder.Entity("LoanApp.Api.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<long>("ApplicationVersion")
                        .HasColumnType("bigint");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeliveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("PolicyRevisionId")
                        .HasColumnType("uuid");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("PolicyRevisionId");

                    b.HasIndex("ApplicationId", "ApplicationVersion")
                        .IsUnique();

                    b.HasIndex("Status", "NextAttemptAtUtc");

                    b.HasIndex("ApplicationId", "ApplicationVersion", "Status");

                    b.ToTable("OutboxMessages", null, t =>
                        {
                            t.HasCheckConstraint("CK_Outbox_Lease", "(\"LeaseToken\" IS NULL) = (\"LeaseExpiresAtUtc\" IS NULL)");

                            t.HasCheckConstraint("CK_Outbox_Operation", "\"Operation\" IN ('Created','Updated')");

                            t.HasCheckConstraint("CK_Outbox_Status", "\"Status\" IN ('Pending','Failed','Delivered')");

                            t.HasCheckConstraint("CK_Outbox_Versions", "\"SchemaVersion\" = 1 AND \"ApplicationVersion\" >= 1 AND \"AttemptCount\" >= 0");
                        });
                });

            modelBuilder.Entity("LoanApp.Api.Infrastructure.Persistence.PolicyHead", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ActiveRevisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BaselineRevisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DraftRevisionId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ActiveRevisionId");

                    b.HasIndex("BaselineRevisionId");

                    b.HasIndex("DraftRevisionId");

                    b.ToTable("PolicyHeads", null, t =>
                        {
                            t.HasCheckConstraint("CK_PolicyHead_Singleton", "\"Id\" = 1 AND \"Version\" >= 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Version = 1L
                        });
                });

            modelBuilder.Entity("LoanApp.Api.Infrastructure.Persistence.PolicyRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BaseRevisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("DraftVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Kind")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BaseRevisionId");

                    b.HasIndex("PublishedAtUtc", "Id");

                    b.ToTable("PolicyRevisions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Policy_Kind", "\"Kind\" IN ('Draft','Published')");

                            t.HasCheckConstraint("CK_Policy_Publication", "(\"Kind\" = 'Published') = (\"PublishedAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Policy_Version", "\"DraftVersion\" >= 1 AND \"SchemaVersion\" = 1");
                        });
                });

            modelBuilder.Entity("LoanApp.Api.Infrastructure.Persistence.LoanApplication", b =>
                {
                    b.HasOne("LoanApp.Api.Infrastructure.Persistence.Customer", null)
                        .WithOne()
                        .HasForeignKey("LoanApp.Api.Infrastructure.Persistence.LoanApplication", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoanApp.Api.Infrastructure.Persistence.PolicyRevision", null)
                        .WithMany()
                        .HasForeignKey("LastPolicyRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LoanApp.Api.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.HasOne("LoanApp.Api.Infrastructure.Persistence.LoanApplication", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LoanApp.Api.Infrastructure.Persistence.PolicyRevision", null)
                        .WithMany()
                        .HasForeignKey("PolicyRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LoanApp.Api.Infrastructure.Persistence.PolicyHead", b =>
                {
                    b.HasOne("LoanApp.Api.Infrastructure.Persistence.PolicyRevision", null)
                        .WithMany()
                        .HasForeignKey("ActiveRevisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LoanApp.Api.Infrastructure.Persistence.PolicyRevision", null)
                        .WithMany()
                        .HasForeignKey("BaselineRevisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LoanApp.Api.Infrastructure.Persistence.PolicyRevision", null)
                        .WithMany()
                        .HasForeignKey("DraftRevisionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LoanApp.Api.Infrastructure.Persistence.PolicyRevision", b =>
                {
                    b.HasOne("LoanApp.Api.Infrastructure.Persistence.PolicyRevision", null)
                        .WithMany()
                        .HasForeignKey("BaseRevisionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
